// <auto-generated />
using System;
using ArumModels.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArumModels.Migrations
{
    [DbContext(typeof(ArumDbContext))]
    [Migration("20210731154506_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "6.0.0-preview.5.21301.9");

            modelBuilder.Entity("ArumModels.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ArumModels.Models.OrderMenu", b =>
                {
                    b.Property<int>("OrderMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OrderMenuId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderMenu");
                });

            modelBuilder.Entity("ArumModels.Models.OrderOption", b =>
                {
                    b.Property<int>("OrderOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("OrderMenuId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OrderOptionId");

                    b.HasIndex("OrderMenuId");

                    b.ToTable("OrderOption");
                });

            modelBuilder.Entity("ArumModels.Models.OrderMenu", b =>
                {
                    b.HasOne("ArumModels.Models.Order", null)
                        .WithMany("MenuList")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("ArumModels.Models.OrderOption", b =>
                {
                    b.HasOne("ArumModels.Models.OrderMenu", null)
                        .WithMany("OptionList")
                        .HasForeignKey("OrderMenuId");
                });

            modelBuilder.Entity("ArumModels.Models.Order", b =>
                {
                    b.Navigation("MenuList");
                });

            modelBuilder.Entity("ArumModels.Models.OrderMenu", b =>
                {
                    b.Navigation("OptionList");
                });
#pragma warning restore 612, 618
        }
    }
}
